version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  up-postman-runner-orb: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-test:
    docker:
      - image: postman/newman:5.3.1
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - up-postman-runner-orb/install_reporter
      - run: |
          npm list -g newman-reporter-testrail
      - up-postman-runner-orb/set_test_run_name
      - run: |
          echo $BASH_ENV
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - command-test:
          filters: *filters
      - up-postman-runner-orb/test:
          context:
            - postman
            - testrail
          filters: *filters
          collection: "https://api.getpostman.com/collections/20634702-00d96313-db26-4c47-bd1c-15948f77681a?apikey=$POSTMAN_API_KEY"
          collection-environment: "https://api.getpostman.com/environments/20634702-ce70ac3d-efdc-48ad-a601-0a47b7ce02b2?apikey=$POSTMAN_API_KEY"
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: tkapuranis/up-postman-runner-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - command-test
            - up-postman-runner-orb/test
          context: orb-publishing
          filters: *release-filters
